POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYWEiLCJpZCI6IjY2ZTFhNTJlMjIxMzIzNDdjNDdhMzMwZiIsImlhdCI6MTcyNjQ5MTQ0OH0.x0cWgziNtIXOCxx8WdEWGprka-jnlXjyFYvy9B6_--U

{
    "title": "xxx",
    "author": "xxx",
    "url": "pizzaonline.fi",
    "likes": 666
}